sudo: false
language: node_js
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - libgnome-keyring-dev
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '5'
before_install:
  - npm i -g npm@latest
install:
  - npm upgrade
before_script:
  - npm run lint
script:
  - npm run build
after_success:
  - npm run autorelease
branches:
  only:
    - "master"
